FROM node:16 AS prod

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY . .

RUN npm install -g typescript
RUN tsc

RUN useradd -m appuser
USER appuser

EXPOSE 3000

CMD ["node", "dist/smartyBot.js"]
